bootstrapServers: "localhost:9092"
# below config is appliciable for newly created topics
replication: 1
partitions: 2
topics:
  - name: Topic4
    retentionMs: 1203
    compression: zstd 
  - name: Topic2
    retentionMs: 1201
    compression: zstd
  - name: Topic234
    retentionMs: 1202
    compression: zstd
      